version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
  pre_build:
    commands:

  build:
    commands:
      - apt-get update -y
      - apt-get install -y docker.io

      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 779846824018.dkr.ecr.ap-south-1.amazonaws.com/first-time:latest
      
      - echo "Building the Docker image..."
      - docker build -t first-time .
      
      - docker tag doc:latest 779846824018.dkr.ecr.ap-south-1.amazonaws.com/first-time:latest
      - echo "Pushing the Docker image to ECR..."
      - docker push 779846824018.dkr.ecr.ap-south-1.amazonaws.com/first-time:latest
      - | 
        echo '[
        {
          "name": "newcontainer",
          "imageUri": "779846824018.dkr.ecr.ap-south-1.amazonaws.com/first-time:latest"
          }
        ]' >imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json